env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
      - darwin
      - freebsd
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
archives:
  - id: zip
    format: zip
    files:
      - LICENSE
      - NOTICE.md
changelog:
  skip: true
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: wata727
    name: packer-post-processor-amazon-ami-management
  draft: true
snapshot:
  name_template: "{{ .Tag }}-dev"
