name: Release

on:
  push:
    branches:
    - '!*'
    tags:
    - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        version: 1.12
    - name: Run GoReleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: v0.116.0
      run: curl -sL https://git.io/goreleaser | bash
